_BASE_: "Base-CenterMask-ResNet.yaml"
MODEL:
  WEIGHTS: "https://nomeroff.net.ua/models/mrcnn/centermask_numberplate_X_101_FPN_ms_3x.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
DATASETS:
  TRAIN: ("numberplate_train",)
  TEST: ("numberplate_val",)
SOLVER:
  STEPS: (0, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/CenterMask-X-101-FPN-ms-3x"
