_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://nomeroff.net.ua/models/detectron2/numberplate_R_50_FPN_3x_2020-12-20.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
