
name: Nomeroff Net CI GPU Benchmark

on:
  push:
    branches: [ master, v3.0, v3.1 ]
  pull_request:
    branches: [  master, v3.0, v3.1 ]

jobs:
  gpu-benchmark:
    runs-on: self-hosted
    #container: docker://dvcorg/cml-py3:latest

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v2

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Get pip cache
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - name: Cache pip
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/cache@v2.1.7
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install dependencies
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python --version
        pip --version
        pip list
      shell: bash

    - name: Run benchmark
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |

        echo "## Benchmarks metrics" > report.md
        cml send-comment report.md

      shell: bash
