
name: Nomeroff Net CI GPU Benchmark

on:
  push:
    branches: [ master, v3.0, v3.1 ]
  pull_request:
    branches: [  master, v3.0, v3.1 ]

jobs:
  gpu-benchmark:
    runs-on: self-hosted
    #container: docker://dvcorg/cml-py3:latest

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: iterative/setup-cml@v1
    - name: Install dependencies
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |

        apt-get install -y libopencv-dev
        apt-get install -y libturbojpeg
        apt-get install -y jupyter-nbconvert
        apt-get install -y python3-notebook
        apt-get install -y jupyter-notebook

        python -m pip install --upgrade pip

        pip install -r requirements.txt
        pip install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html
        pip3 install tqdm==4.40.0

        # extras
        pip install setuptools wheel pytest

        python --version
        pip --version
        pip list

      shell: bash

    - name: Run benchmark
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |

        echo "# Benchmarks" > report.md

        echo "# Benchmark accuracy" > report.md
        CUDA_VISIBLE_DEVICES=0 python examples/py/benchmark/accuracy-test.py \
            --pipeline_name=number_plate_detection_and_reading \
            --image_loader_name=turbo \
            --images_glob=./data/examples/benchmark_oneline_np_images/* \
            --test_file=./data/examples/accuracy_test_data.json \
            >> report.md

        echo "# Benchmark runtime" > report.md
        CUDA_VISIBLE_DEVICES=0 python examples/py/benchmark/runtime-test.py \
            --pipeline_name=number_plate_detection_and_reading_runtime \
            --image_loader_name=turbo \
            --images_glob=./data/examples/benchmark_oneline_np_images/* \
            --res_file=./data/examples/runtime_test_report.json \
            --num_run=10 \
            --overclock_num_run=2 \
            --batch_size=1 \
            --num_workers=1
        ./data/examples/runtime_test_report.json >> report.md

        cml-send-comment report.md

      shell: bash
