
name: Nomeroff Net CI GPU Benchmark

on:
  push:
    branches: [ master, v3.0, v3.1 ]
  pull_request:
    branches: [  master, v3.0, v3.1 ]

jobs:
  gpu-benchmark:
    runs-on: self-hosted
    #container: docker://dvcorg/cml-py3:latest

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: iterative/setup-cml@v1
    - name: Install dependencies
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python --version
        pip --version
        pip list
      shell: bash

    - name: Run benchmark
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |

        echo "## Benchmarks metrics" > report.md
        cml-send-comment report.md

      shell: bash
