# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Nomeroff Net CI GPU Testing

on:
  push:
    branches: [ master, v3.0, v3.1 ]
    paths:
      - 'nomeroff_net/**'
      - 'examples/**'
  pull_request:
    branches: [  master, v3.0, v3.1 ]
    paths:
      - 'nomeroff_net/**'
      - 'examples/**'
  schedule:
    - cron: '10 0 * * *'  # Runs at 00:10 UTC every day

jobs:
  gpu-tests:
    runs-on: [self-hosted,cml,gpu]
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        nvidia-smi
